/**
 * MIT License
 * 
 * Copyright (c) 2022 Zenklub
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 * 
 * 
 * Do not edit directly
 * Generated on Wed, 31 Aug 2022 19:34:14 GMT
*/

public enum FreudDSFreudicons: String, CaseIterable {
  case accessible = "\u{f101}"
  case adjustmentsHorizontal = "\u{f102}"
  case adjustments = "\u{f103}"
  case alertCircle = "\u{f104}"
  case alertOctagon = "\u{f105}"
  case apps = "\u{f106}"
  case archive = "\u{f107}"
  case arrowDownCircle = "\u{f108}"
  case arrowDownLeftCircle = "\u{f109}"
  case arrowDownLeft = "\u{f10a}"
  case arrowDownRightCircle = "\u{f10b}"
  case arrowDownRight = "\u{f10c}"
  case arrowDown = "\u{f10d}"
  case arrowLeft = "\u{f10e}"
  case arrowRight = "\u{f10f}"
  case arrowUpCircle = "\u{f110}"
  case arrowUpLeftCircle = "\u{f111}"
  case arrowUpLeft = "\u{f112}"
  case arrowUpRightCircle = "\u{f113}"
  case arrowUpRight = "\u{f114}"
  case arrowUp = "\u{f115}"
  case arrowsRightLeft = "\u{f116}"
  case at = "\u{f117}"
  case award = "\u{f118}"
  case ballon = "\u{f119}"
  case ban = "\u{f11a}"
  case bandage = "\u{f11b}"
  case barcode = "\u{f11c}"
  case beach = "\u{f11d}"
  case bellOff = "\u{f11e}"
  case bellRinging = "\u{f11f}"
  case bell = "\u{f120}"
  case bookmarkOff = "\u{f121}"
  case bookmark = "\u{f122}"
  case box = "\u{f123}"
  case brandAndroid = "\u{f124}"
  case brandApple = "\u{f125}"
  case brandFacebook = "\u{f126}"
  case brandFigma = "\u{f127}"
  case brandGithub = "\u{f128}"
  case brandGoogleDrive = "\u{f129}"
  case brandGooglePlay = "\u{f12a}"
  case brandInstagram = "\u{f12b}"
  case brandLinkedin = "\u{f12c}"
  case brandNetflix = "\u{f12d}"
  case brandTwitter = "\u{f12e}"
  case brandWhatsapp = "\u{f12f}"
  case brandYoutube = "\u{f130}"
  case browser = "\u{f131}"
  case buildingBank = "\u{f132}"
  case buildingCastle = "\u{f133}"
  case buildingChurch = "\u{f134}"
  case buildingCommunity = "\u{f135}"
  case buildingCottage = "\u{f136}"
  case buildingFactory = "\u{f137}"
  case buildingFortress = "\u{f138}"
  case buildingHospital = "\u{f139}"
  case buildingPavilon = "\u{f13a}"
  case buildingSkyscraper = "\u{f13b}"
  case buildingStore = "\u{f13c}"
  case buildingWarehouse = "\u{f13d}"
  case building = "\u{f13e}"
  case bulb = "\u{f13f}"
  case businessplan = "\u{f140}"
  case calculator = "\u{f141}"
  case calendarEvent = "\u{f142}"
  case calendarTime = "\u{f143}"
  case calendar = "\u{f144}"
  case cameraOff = "\u{f145}"
  case camera = "\u{f146}"
  case car = "\u{f147}"
  case certificate = "\u{f148}"
  case chartBar = "\u{f149}"
  case chartPie2 = "\u{f14a}"
  case check = "\u{f14b}"
  case checkbox = "\u{f14c}"
  case chevronDown = "\u{f14d}"
  case chevronLeft = "\u{f14e}"
  case chevronRight = "\u{f14f}"
  case chevronUp = "\u{f150}"
  case circleCheck = "\u{f151}"
  case circleMinus = "\u{f152}"
  case circlePlus = "\u{f153}"
  case circleX = "\u{f154}"
  case clipboardCheck = "\u{f155}"
  case clipboardList = "\u{f156}"
  case clipboardX = "\u{f157}"
  case clock = "\u{f158}"
  case cloudDownload = "\u{f159}"
  case cloudRain = "\u{f15a}"
  case cloudStorm = "\u{f15b}"
  case cloudUpload = "\u{f15c}"
  case cloud = "\u{f15d}"
  case code = "\u{f15e}"
  case coffee = "\u{f15f}"
  case coin = "\u{f160}"
  case copy = "\u{f161}"
  case creditCard = "\u{f162}"
  case currencyDollar = "\u{f163}"
  case database = "\u{f164}"
  case deviceDesktop = "\u{f165}"
  case deviceLaptop = "\u{f166}"
  case deviceMobile = "\u{f167}"
  case deviceTablet = "\u{f168}"
  case deviceTv = "\u{f169}"
  case deviceWatch = "\u{f16a}"
  case devices2 = "\u{f16b}"
  case devicesPc = "\u{f16c}"
  case devices = "\u{f16d}"
  case diamond = "\u{f16e}"
  case disabled = "\u{f16f}"
  case discount2 = "\u{f170}"
  case discount = "\u{f171}"
  case dotsVertical = "\u{f172}"
  case dots = "\u{f173}"
  case edit = "\u{f174}"
  case externalLink = "\u{f175}"
  case eyeOff = "\u{f176}"
  case eye = "\u{f177}"
  case faceId = "\u{f178}"
  case fileCertificate = "\u{f179}"
  case fileText = "\u{f17a}"
  case filterOff = "\u{f17b}"
  case filter = "\u{f17c}"
  case fingerprint = "\u{f17d}"
  case flag = "\u{f17e}"
  case folder = "\u{f17f}"
  case folders = "\u{f180}"
  case ghost = "\u{f181}"
  case gift = "\u{f182}"
  case gridDots = "\u{f183}"
  case handRock = "\u{f184}"
  case headphonesOff = "\u{f185}"
  case headphones = "\u{f186}"
  case heartFill = "\u{f187}"
  case heart = "\u{f188}"
  case help = "\u{f189}"
  case history = "\u{f18a}"
  case home = "\u{f18b}"
  case infinity = "\u{f18c}"
  case infoCircle = "\u{f18d}"
  case layoutGridAdd = "\u{f18e}"
  case layoutGrid = "\u{f18f}"
  case layoutSidebar = "\u{f190}"
  case license = "\u{f191}"
  case link = "\u{f192}"
  case listCheck = "\u{f193}"
  case listSearch = "\u{f194}"
  case list = "\u{f195}"
  case liveView = "\u{f196}"
  case loader = "\u{f197}"
  case location = "\u{f198}"
  case lockOff = "\u{f199}"
  case lockOpen = "\u{f19a}"
  case lock = "\u{f19b}"
  case login = "\u{f19c}"
  case logout = "\u{f19d}"
  case mailOpened = "\u{f19e}"
  case mail = "\u{f19f}"
  case mapPinOff = "\u{f1a0}"
  case mapPin = "\u{f1a1}"
  case menu = "\u{f1a2}"
  case messageCircleOff = "\u{f1a3}"
  case messageCircle = "\u{f1a4}"
  case messages = "\u{f1a5}"
  case microphoneOff = "\u{f1a6}"
  case microphone = "\u{f1a7}"
  case minus = "\u{f1a8}"
  case moodConfuzed = "\u{f1a9}"
  case moodCrazyHappy = "\u{f1aa}"
  case moodEmpty = "\u{f1ab}"
  case moodHappy = "\u{f1ac}"
  case moodSad = "\u{f1ad}"
  case moodSmile = "\u{f1ae}"
  case moodSuprised = "\u{f1af}"
  case moodTongue = "\u{f1b0}"
  case moon = "\u{f1b1}"
  case motorbike = "\u{f1b2}"
  case movie = "\u{f1b3}"
  case mug = "\u{f1b4}"
  case music = "\u{f1b5}"
  case paperclip = "\u{f1b6}"
  case peace = "\u{f1b7}"
  case pencil = "\u{f1b8}"
  case phoneOff = "\u{f1b9}"
  case phone = "\u{f1ba}"
  case photo = "\u{f1bb}"
  case pill = "\u{f1bc}"
  case pills = "\u{f1bd}"
  case pin = "\u{f1be}"
  case pinnedOff = "\u{f1bf}"
  case pinned = "\u{f1c0}"
  case pizza = "\u{f1c1}"
  case plane = "\u{f1c2}"
  case plant2 = "\u{f1c3}"
  case plant = "\u{f1c4}"
  case playerPause = "\u{f1c5}"
  case playerPlay = "\u{f1c6}"
  case playlist = "\u{f1c7}"
  case plus = "\u{f1c8}"
  case power = "\u{f1c9}"
  case printer = "\u{f1ca}"
  case puzzle = "\u{f1cb}"
  case qrcode = "\u{f1cc}"
  case receipt2 = "\u{f1cd}"
  case receiptOff = "\u{f1ce}"
  case receipt = "\u{f1cf}"
  case refresh = "\u{f1d0}"
  case reportMoney = "\u{f1d1}"
  case report = "\u{f1d2}"
  case rocket = "\u{f1d3}"
  case rotateClockwise = "\u{f1d4}"
  case school = "\u{f1d5}"
  case search = "\u{f1d6}"
  case send = "\u{f1d7}"
  case settings = "\u{f1d8}"
  case share = "\u{f1d9}"
  case shieldCheck = "\u{f1da}"
  case shoppingCart = "\u{f1db}"
  case snowflake = "\u{f1dc}"
  case speakerphone = "\u{f1dd}"
  case stack = "\u{f1de}"
  case starFill = "\u{f1df}"
  case starHalf = "\u{f1e0}"
  case starOff = "\u{f1e1}"
  case star = "\u{f1e2}"
  case sun = "\u{f1e3}"
  case switchVertical = "\u{f1e4}"
  case thumbDown = "\u{f1e5}"
  case thumbUp = "\u{f1e6}"
  case ticket = "\u{f1e7}"
  case trashOff = "\u{f1e8}"
  case trash = "\u{f1e9}"
  case trophy = "\u{f1ea}"
  case unlink = "\u{f1eb}"
  case upload = "\u{f1ec}"
  case urgent = "\u{f1ed}"
  case userCircle = "\u{f1ee}"
  case user = "\u{f1ef}"
  case users = "\u{f1f0}"
  case vaccine = "\u{f1f1}"
  case videoOff = "\u{f1f2}"
  case video = "\u{f1f3}"
  case volume2 = "\u{f1f4}"
  case volume3 = "\u{f1f5}"
  case volume = "\u{f1f6}"
  case wallet = "\u{f1f7}"
  case wifiOff = "\u{f1f8}"
  case wifi = "\u{f1f9}"
  case world = "\u{f1fa}"
  case x = "\u{f1fb}"
  case yinYang = "\u{f1fc}"

  public static let font = FontRegister.register(at: "FreudIcons", named: "freud-icons")
}
