image: node:14

stages:
  - build
  - test
  - quality
  - release

.except-post-publish:
  except: &except-post-publish
    variables:
      - $CI_COMMIT_TITLE =~ /^chore\(release\):\sautomatic\sversion\supdate$/

#########
# Build #
#########
prepare:
  stage: build
  retry:
    max: 2
    when: runner_system_failure
  script:
    - npm i -g nx@11
    - npm ci --quiet
    - npm run build
    - npm run build:freud-core
  artifacts:
    expire_in: 1 week
    paths:
      - node_modules/
  except: *except-post-publish
  only:
    - merge_requests
    - feat/*
    - feature/*
    - fix/*
    - hotfix/*
    - master
    - main
    - develop

########
# Lint #
########
lint:
  stage: test
  retry:
    max: 2
    when: runner_system_failure
  dependencies:
    - prepare
  script:
    - npm run lint
  except: *except-post-publish
  only:
    - merge_requests
    - feat/*
    - feature/*
    - fix/*
    - hotfix/*
    - master
    - main
    - develop

include:
  - '/ci/gitlab/release-core.yml'
