image: ${CI_REGISTRY_IMAGE}/freud-builder:latest

stages:
  - docker images
  - build
  - quality
  - release

include:
  - '/ci/gitlab/docker.yml'
  - '/ci/gitlab/build.yml'
  # - '/ci/gitlab/release-core.yml'
