#########
# Build #
#########
prepare:
  cache:
    paths:
    - node_modules/
    - libs/**/node_modules/
    - apps/**/node_modules/
  stage: build
  retry:
    max: 2
    when: runner_system_failure
  script:
    - npm ci --quiet
    - npm run build
    - npm run build:core-support
  artifacts:
    expire_in: 1 week
    paths:
      - node_modules/

########
# Lint #
########
lint:
  stage: test
  retry:
    max: 2
    when: runner_system_failure
  dependencies:
    - prepare
  script:
    - npm run lint
