
#########
# Build #
#########
build:
  cache:
    key:
      files:
        - package-lock.json
    paths:
    - node_modules/
  stage: build
  retry:
    max: 2
    when: runner_system_failure
  script:
    - npm ci --quiet --no-optional
    - npm run build:tokens
  artifacts:
    expire_in: 1 week
    paths:
      - node_modules/

