name: On Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  quality_gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/quality-gate
