name: Tokens - build and publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: Nova versão
        default: patch
        required: true
        type: choice
        options:
          - patch
          - minor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          cd packages/tokens
          npm install

      - name: Configure git
        run: |
          git config user.email "bot@zenklub.com"
          git config user.name "Zenklub Deploy Bot"

      - name: Update version
        run: |
          cd packages/tokens
          npm version ${{ github.event.inputs.version }}

      - name: Push new version
        run: |
          git add .
          git commit -m "chore(tokens): automatic version update"
          git remote set-url origin https://${{ secrets.FREUD_DS_GITHUB_PAT }}@github.com:Zenklub/freud-ds.git
          git push

      - name: Build
        run: npm run build:tokens

      - name: Publish
        run: |
          cd packages/tokens/dist
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          echo "unsafe-perm = true" >> ~/.npmrc
          npm publish --access public

        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
